apiVersion: v1
kind: Service
metadata:
  name: nike-service
spec:
  type: LoadBalancer
  selector:
    app: nikee
  ports:
    - port: 80
      targetPort: 80
      protocol: "TCP"

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: LoadBalancer
  selector:
    app: nikee-server
  ports:
    - port: 4000
      targetPort: 4000
      protocol: "TCP"

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: ClusterIP
  selector:
    app: mongo-server
  ports:
    - port: 27017
      targetPort: 27017
