export const productInitialState = {
  aboutProduct: "",
  productInformation: "",
  productsType: "Mens",
  productCategory: "Shoes",
  productSize: [],
  images: [],
  imagesR: [],
  image: "",
  imageR: "",
  name: "",
  amount: 0,
  discount: 0,
  color: "",
  brands: "",
  featured: false,
  sale: false,
};

export const sneakerInitialState = {
  aboutSneaker: "",
  sneakerInformation: "",
  sneakerType: "Mens",
  size: [],
  heroImage: [],
  imagesR: [],
  image: "",
  imageR: "",
  name: "",
  amount: 0,
  discount: 0,
  color: "",
  brands: "",
  featured: false,
  sale: false,
  productCategory: "Shoes",
};
